name: tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up John
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install john-jumbo
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Setup Python & Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: "3.11"
          poetry-version: "1.6.1"

      - name: Run tests
        run: |
          poetry run task test
